export default {
    exam: 'Quiz',
    name: 'Nama',
    examDate: 'Tanggal quiz',
    examTime: 'Waktu',
    totalQuestions: 'Total pertanyaan',
    questions: 'Pertanyaan',
    supervisors: 'Pengawas',
    search: 'Cari',
    joinedSupervisors: 'Pengawas yang bergabung',
    allSupervisors: 'Semua pengawas',
    save: 'Simpan',
    delete: 'Hapus',
    maxChapterQuestionCount: 'Bab @name hanya memiliki @questionNumber pertanyaan.',
    deleteMessage: 'Apakah Anda yakin ingin menghapus quiz ini? Tindakan ini tidak dapat dibatalkan.',
    langYes: 'Ya',
    langNo: 'Tidak',
    viewInExamsPage: 'Lihat di halaman quiz',
};
