export default {
    dashboard: 'Dashboard',
    subjects: 'Mata pelajaran',
    courses: 'Kursus',
    schoolClass: 'Kelas',
    faculty: 'Fakultas',
    profile: 'Profil',
    exams: 'Quiz',
    questions: 'Pertanyaan',
    admins: 'Admin',
    teachers: 'Guru',
    students: 'Siswa',
    permission: 'Izin',
    semester: 'Semester',
    settings: 'Pengaturan',
    term: 'Syarat',
    privacy: 'Privasi',
    security: 'Keamanan',
    contact: 'Kontak',
    docs: 'Dokumen',
};
